[package]
name = "sloppy"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Bryant Luk <code@bryantluk.com>"]
edition = "2018"
description = "A sloppy distributed hash table library"
repository = "https://github.com/bluk/sloppy"
readme = "README.md"
include = [
  "src/**/*.rs",
  "Cargo.toml",
  "README.md",
  "LICENSE-APACHE",
  "LICENSE-MIT",
]

[dependencies]
bt_bencode = "0.2"
serde = { version = "1", features=["derive"] }
serde_bytes = "0.11"
itoa = "0.4"
rand = "0.8"
crc32c = "0.6"
log = "0.4"

[dev-dependencies]
mio = {version = "0.7", features = ["os-poll", "udp"] }
env_logger = "0.8"
clap = "2"
