name: Rust Stable on Windows

on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  check:
    name: Check
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.38.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Rust Version
        run: rustc --version
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  test:
    name: Test
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.38.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Rust Version
        run: rustc --version
      - name: Run cargo test
        run: cargo test
  rustfmt:
    name: Format
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.38.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Rust Version
        run: rustc --version
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Clippy
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.38.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Install clippy
        run: rustup component add clippy
      # - name: Run cargo clippy
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: clippy
      #     args: -- -D warningsadd clippy
      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
